# Site settings

title: Jason의 안드로이드 이야기. # Title of your site
email: yong076@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yong076.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     yong076  # Replace this with your Twitter username
github_username:      yong076  # Replace this with your GitHub username
linkedin_username:    yong076  # Replace this with your LinkedIn username
google_plus_username: yong076  # Replace this with your Google+ username
facebook_username:    yong076  # Replace this with your Facebook username

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge